<?php
//Company Profile
define("APP_NAME", CONFIG("APP_NAME"));
define("COMPANY_NAME", CONFIG("COMPANY_NAME"));
define("APP_LOGO", STORAGE_URL . "/company/img/logo/" . CONFIG("APP_LOGO"));
define("LOGIN_BG_IMAGE", STORAGE_URL_D . "/bg/" . CONFIG("LOGIN_BG_IMAGE"));
define("TAGLINE", CONFIG("TAGLINE"));
define("OWNER_NAME", CONFIG("OWNER_NAME"));
define("PRIMARY_PHONE", CONFIG("PRIMARY_PHONE"));
define("PRIMARY_EMAIL", CONFIG("PRIMARY_EMAIL"));
define("SHORT_DESCRIPTION", CONFIG("SHORT_DESCRIPTION"));
define("PRIMARY_ADDRESS", CONFIG("PRIMARY_ADDRESS"));
define("PRIMARY_AREA", CONFIG("PRIMARY_AREA"));
define("PRIMARY_CITY", CONFIG("PRIMARY_CITY"));
define("PRIMARY_STATE", CONFIG("PRIMARY_STATE"));
define("PRIMARY_PINCODE", CONFIG("PRIMARY_PINCODE"));
define("PRIMARY_COUNTRY", CONFIG("PRIMARY_COUNTRY"));
define("PRIMARY_MAP_LOCATION_LINK", CONFIG("PRIMARY_MAP_LOCATION_LINK"));
define("PRIMARY_GST", CONFIG("GST_NO"));
define("COMPANY_TYPE", CONFIG("COMPANY_TYPE"));
define("FINANCIAL_YEAR", CONFIG("FINANCIAL_YEAR"));
define("GST_NO", CONFIG("GST_NO"));
define("APP_THEME", CONFIG("APP_THEME"));

//mail id's setups
define("SENDER_MAIL_ID", CONFIG("SENDER_MAIL_ID"));
define("RECEIVER_MAIL", CONFIG("RECEIVER_MAIL"));
define("REPLY_TO", CONFIG("REPLY_TO"));
define("SUPPORT_MAIL", CONFIG("SUPPORT_MAIL"));
define("ENQUIRY_MAIL", CONFIG("ENQUIRY_MAIL"));
define("ADMIN_MAIL", CONFIG("ADMIN_MAIL"));

//downloadable & add-on links
define("DOWNLOAD_ANDROID_APP_LINK", CONFIG("DOWNLOAD_ANDROID_APP_LINK"));
define("DOWNLOAD_IOS_APP_LINK", CONFIG("DOWNLOAD_IOS_APP_LINK"));
define("DOWNLOAD_BROCHER_LINK", CONFIG("DOWNLOAD_BROCHER_LINK"));

//control activity or die activities, function 
define("CONTROL_WORK_ENV", CONFIG("CONTROL_WORK_ENV"));
define("CONTROL_SMS", CONFIG("CONTROL_SMS"));
define("CONTROL_MAILS", CONFIG("CONTROL_MAILS"));
define("CONTROL_APP_LOGS", CONFIG("CONTROL_APP_LOGS"));
define("WEBSITE", CONFIG("WEBSITE"));
define("APP", CONFIG("APP"));

//payment gateway configurations
define("PG_OPTIONS", array("RAZORAPAY"));
define("ONLINE_PAYMENT_OPTION", CONFIG("ONLINE_PAYMENT_OPTION"));
define("PG_MODE", CONFIG("PG_MODE"));
define("PG_PROVIDER", CONFIG("PG_PROVIDER"));
define("MERCHENT_ID", CONFIG("MERCHENT_ID"));
define("MERCHANT_KEY", CONFIG("MERCHANT_KEY"));
define("MAX_ORDER_QTY", CONFIG("MAX_ORDER_QTY"));
define("MIN_ORDER_QTY", CONFIG("MIN_ORDER_QTY"));

//default variables
define("DEFAULT_USER_ICON", STORAGE_URL_D . "/default/default.png");
